FROM ubuntu:18.04
USER root
ENV DEBIAN_FRONTEND=noninteractive
ENV LANG C.UTF-8
RUN apt-get update
COPY requirement.base.txt /workspace/requirement.base.txt
COPY requirement.txt /workspace/requirement.txt
COPY apt_install.sh /workspace/apt_install.sh
RUN bash /workspace/apt_install.sh
RUN pip3 install -r /workspace/requirement.base.txt
RUN pip3 install -r /workspace/requirement.txt
ADD ezdxf.tar.bz2 /
RUN cd /ezdxf; python3 setup.py install
WORKDIR /root
